config/routes.rb
SomethingOverflow::Application.routes.draw do
  resources :sessions, :only => [:new, :create, :destroy]

  resources :users, :except => :index
  
  resources :questions, :except => [:edit, :update, :destroy]
  post 'questions/best' => 'questions#best'

  resources :answers, :only => [:create]

  resources :comments, :only => [:create, :edit, :update, :destroy]
  resources :votes, only: [:create, :update]

  root :to => 'questions#index'
  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_many :comments
  has_many :votes, as: :voteable
  
  before_save :answer_scraper

  attr_accessible :url, :content, :question, :user

  validates :url, presence: true
  validate :must_be_amazon_url

  default_scope order('created_at DESC')

  def best?
    self.id == self.question.best_answer 
  end

  def vote_count 
    self.votes.inject(0) { |result, vote| result + vote.value}
  end

  def answer_scraper
    agent = Mechanize.new
    agent.get(self.url)
    self.picture_url = agent.page.search("#main-image").first.attributes['src'].value
    mech_objs = agent.page.search("h1").children
    self.product_name = mech_objs.length > 1 ? mech_objs[-2].text() : mech_objs.text()
  end

  def must_be_amazon_url
    unless url =~ /http:\/\/www.amazon.com\S*/
      errors.add(:url, "must begin with 'http://amazon.com'")
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :answer
  has_many   :votes, as: :voteable

  attr_accessible :content, :user, :answer
  validates :content, presence: true

  default_scope order('created_at DESC')

  def vote_count 
    self.votes.inject(0) { |result, vote| result + vote.value}
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers

  attr_accessible :title, :content, :user, :answer, :best_answer
  validates :title, :content, presence: true
  default_scope order('created_at DESC')

  def owner?(current_user)
  	current_user.id == self.user_id
  end

  def sorted_answers
    answers = self.answers.sort!{ |a,b| b.vote_count <=> a.vote_count }
    return answers if self.best_answer.nil?
    answers.partition { |answer| answer.id == self.best_answer }.flatten
  end

 end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :votes
  has_many :answers
  has_many :comments

  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  validates :name, :email, :password, presence: true
  validates :email, uniqueness: true

  def find_vote(voteable)
    self.votes.find_by_voteable_id_and_voteable_type(voteable.id, voteable.class.name)
  end

  def vote_value(voteable)
    vote = find_vote(voteable)
    vote ? vote.value : 0
  end

  def vote_id(voteable)
    vote = find_vote(voteable)
    vote ? vote.id : 0
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :voteable, polymorphic: true
  belongs_to :user

  attr_accessible :value, :user_id, :voteable_id, :voteable_type
  validates_uniqueness_of :user_id, :scope => [:voteable_id, :voteable_type]
  validates :voteable_type, :voteable_id, :presence => :true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    params[:answer][:question] = Question.find(params[:answer].delete(:question_id))
    params[:answer][:user] = current_user
    answer = Answer.create(params[:answer])
    if answer.valid?
      @comment = Comment.new
      render :json => render_to_string(:partial => 'answer', :locals => { :answer => answer, :@comment => @comment }).to_json
    else
      render :json => render_to_string(:partial => 'layouts/errors', :locals => { :bad_object => answer }), :status => :unprocessable_entity
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def create_session(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def store_return_to
    session[:return_to] = request.referer unless session[:return_to]
  end

  def redirect_back_or_default(default)
    redirect_to(session[:return_to] || default)
    session[:return_to] = nil
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    params[:comment][:answer] = Answer.find(params[:comment].delete(:answer_id))
    params[:comment][:user] = current_user
    comment = Comment.create(params[:comment])
    if comment.valid?
      render :json => render_to_string(:partial => 'comment', :locals => { :comment => comment }).to_json
    else
      render :json => render_to_string(:partial => 'layouts/errors', :locals => { :bad_object => comment }), :status => :unprocessable_entity
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def new
    if current_user
      @question = Question.new
    else
      session[:return_to] = request.url
      redirect_to new_session_path
    end
  end

  def create
    @question = Question.new(params[:question])
    current_user.questions << @question
    if @question.save
      redirect_to @question
    else
      flash.now[:errors] = @question.errors.full_messages
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    @comment = Comment.new
  end

  def best
    answer = Answer.find(params[:answer])
    question = answer.question
    question.best_answer = answer.id
    question.save
    render partial: 'answers/best'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :store_return_to, :only => [:new]

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email]) 
    if user && user.authenticate(params[:session][:password])
      create_session(user)
      redirect_back_or_default user
    else
      flash.now[:errors] = ["Wrong username or password"]
      render :new
    end
  end

  def destroy 
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :store_return_to, :only => [:new]

  def new
    if current_user
      redirect_to current_user
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      create_session(@user)
      redirect_back_or_default @user
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = current_user
    redirect_to current_user unless User.find(params[:id]) == @user
  end

  def update
    @user = current_user
    @user.assign_attributes(params[:user])
    if @user.save
      redirect_to @user
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def destroy
    current_user.destroy
    redirect_to root_path
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  include ActionView::Helpers::TextHelper

  def create
    vote = Vote.create(params[:vote])
    current_user.votes << vote
    render :json => { vote_id: vote.id, vote_count: vote_count(params[:vote][:voteable_type], params[:vote][:voteable_id]) }
  end

  def update
    vote = Vote.find(params[:id])
    vote.update_attributes(params[:vote])
    render :json => { vote_count: vote_count(params[:vote][:voteable_type], params[:vote][:voteable_id]) }
  end

  protected
    def vote_count(voteable_type, voteable_id)
      eval(voteable_type).find(voteable_id).vote_count
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_answer.html.erb
<div class="answer-box">
  <div class="answer" <% if answer.best? %>id="best-answer"<% end %>>    
    <%= render 'answers/details', answer: answer %>
    <%= render 'answers/choose_best', answer: answer %>

    <%= render 'votes/vote_box', voteable: answer %>

    <%= render 'answers/comment_details', answer: answer %>

    <div class="float-clear"></div>
    <%= render 'comments/comment_box', answer: answer  %>
  </div>
  
</div>

app/views/answers/_answer_count.html.erb
<p id="num-of-answers"><%= pluralize(question.answers.length, "Answer") %></p>

app/views/answers/_answer_count_home.html.erb
<p class="word-answers"><%= question.answers.length == 1 ? "answer" : "answers" %></p>

app/views/answers/_best.html.erb
<h2>Best Answer</h2>

app/views/answers/_choose_best.html.erb
<% if current_user && answer.question.owner?(current_user) %>
  <%= link_to "BEST ANSWER", 
      questions_best_path(:answer => answer.id), 
      :method => :post, 
      remote: true, 
      :class => "best_answer" 
  %>
<% end %>

app/views/answers/_comment_details.html.erb
<div class="num-comment-box">
  <div class="num-comments"><%= answer.comments.length %></div>
  <div class="word-comments"><%= answer.comments.length == 1 ? "comment" : "comments" %></div>
</div>
<% unless ( answer.comments.length == 0 ) && !current_user %>
  <%= link_to "Add/View Comments", question_path(answer.question), :class => "comment-toggle" %>
<% end %>

app/views/answers/_details.html.erb
<div class="product-details">
  <%= image_tag answer.picture_url, height: '200', width: '200', :class => "answer-image" %>
  <p><b>Product Name:</b> <%= link_to answer.product_name, answer.url %></p>
  <p class="answer-content"><b>Review:</b> <%= answer.content %></p>
  <p class="answer-timestamp">answered <%= time_ago_in_words(answer.created_at) %> ago</p>
  <%= link_to answer.user.name, user_path(answer.user), :class => "answer-user" %>
</div>

app/views/answers/_form.html.erb
<div id="errors"></div>
<%=  form_for(@answer, remote: true) do |f| %>
  <%=  f.text_area :content, :placeholder => "Comment", :class => "form-input", :id => "form-comment" %>
  <%=  f.text_field :url, :placeholder => "Amazon URL", :class => "form-input", :id => "form-url" %>
  <%=  f.hidden_field :question_id, :value => question.id %>
  <%=  f.submit "Post Answer", :class => "form-button" %>
<% end %>

app/views/comments/_comment.html.erb
<div class="comment">
  <div class="comment-details">
    <div class="comment-text"><%= comment.content %></div>
    <p class="comment-timestamp">commented <%= time_ago_in_words(comment.created_at) %> ago</p>
    <%= link_to comment.user.name, user_path(comment.user), :class => "comment-user" %>
  </div>
  <%= render 'votes/vote_box', voteable: comment %>
</div>

app/views/comments/_comment_box.html.erb
<div class="comments">
  <% if current_user %>
    <%= render 'comments/form', answer: answer  %>
  <% end %> 
  <div class='comment-box'>
    <% answer.comments.each do |comment| %>
      <%= render 'comments/comment', comment: comment  %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<div id="errors"></div>
<div class="comment-form">
  <%= form_for(@comment, remote: true) do |f| %>
    <%= f.text_field :content, :class => "form-input" %>
    <%= f.hidden_field :answer_id, value: answer.id %>
    <%= f.submit "Add Comment", :class => "form-button" %>
  <% end %>
</div>

app/views/layouts/_errors.html.erb
<div class="errors">
  <div class="error-header">Please fix the following errors:</div>
  <% bad_object.errors.full_messages.each do |error| %>
    <li class="error"><%= error %></li>
  <% end %>
</div>

app/views/layouts/_flash_errors.html.erb
<% if flash[:errors] %>
  <div class="errors">
    <div class="error-header">Please fix the following errors:</div>
    <% flash[:errors].each do |error| %>
      <li class="error"><%= error %></li>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!-- REVIEW: there is too much going on here, user partials to organize this view -->

<!DOCTYPE html>
<html>
  <head>
    <title>Something Overflow</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <link href='http://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <div id="nav-links">
        <% if current_user %>
          <%= link_to "logout", session_path(current_user), :method => :delete, :class => "nav-button" %>
          <%= link_to "profile", user_path(current_user), :class => "nav-button" %>
        <% else %>
          <%= link_to "login", new_session_path, :class => "nav-button" %>
          <%= link_to "sign up", new_user_path, :class => "nav-button" %>
        <% end %>
      </div>
    </header>
    <div id="container">
      <div id="logo-ask-box">
          <%= link_to "something overflow", root_path, :id => "home-button" %>
          <%= link_to "Ask Question", new_question_path, :id => "ask-button" %>
      </div>
      <div id="yield">
        <div id="page-title-box">
        <%= yield %>
      </div>
    </div>
    <footer>Created by: Avanish, Paulette, Phil & Shiv</footer>
  </body>
</html>

app/views/questions/_answer_form.html.erb
<div id="create-new-answer">
  <p id="your-answer">Your Answer</p>
  <%= render 'answers/form', :question => question %>
</div>

app/views/questions/_index.html.erb
<div id="all-questions">
  <% questions.each do |question| %>
    <div class="question-box">
      <div class="answers-box">
        <p class="num-answers"><%= question.answers.length %></p>
        <%= render 'answers/answer_count_home', :question => question %>
      </div>
      <div class="question-details-box">
        <div class="question-title-box">
          <%= link_to question.title, question_path(question) %>
        </div>
        <div class="question-user-box">
          <%= link_to question.user.name, user_path(question.user.id), :class => "question-user" %>
          <p class="timestamp"><%= time_ago_in_words(question.created_at) %> ago</p>
        </div>
      </div>
      <div class="float-clear"></div>
    </div>
  <% end %>
</div>

app/views/questions/_question_answers.html.erb
<div id="answers-container">
  <div id="answers-box-header">
    <%= render 'answers/answer_count', :question => question %>
  </div>
  <div id="answers-box">
    <% question.sorted_answers.each do |answer| %>
      <%= render 'answers/answer', :answer => answer %>
    <% end %>
  </div>
</div>

app/views/questions/_question_details.html.erb
<div id="question-details-box">
  <div id="details-box">
    <%= link_to question.user.name, user_path(question.user.id), :class => "question-user" %>
    <p class="timestamp">asked <%= time_ago_in_words(question.created_at) %> ago</p>
  </div>
</div>

app/views/questions/_question_title.html.erb
<div id="question-description-box">
  <p><%= question.content %></p>
</div>

app/views/questions/index.html.erb
  <p id="standard-page-title">All Questions</p>
</div>
<%= render 'questions/index', :questions => @questions %>

app/views/questions/new.html.erb
  <p id="standard-page-title">Post New Question</p>
</div>
<%= render 'layouts/flash_errors' %>
<div id="question-form">
  <%= form_for @question do |f| %>
    <%= f.text_field :title, :class => "form-input", :id => "question-title", :placeholder => 'Title' %>
    <%= f.text_area :content, :class => "form-input", :id => "question-content", :placeholder => 'Content' %>
    <%= f.submit "Create Question", :class => "form-button" %>
  <% end %>
</div>

app/views/questions/show.html.erb
<p id="question-show-page-title"><%= @question.title %></p>
</div>

<%= render 'question_title', :question => @question %>
<%= render 'question_details', :question => @question %>

<% if current_user %>
  <%= render 'answer_form', :question => @question %>
<% end %>

<%= render 'question_answers', :question => @question %>

app/views/users/_form.html.erb
<div id="login-signup-form">
  <%= form_for @user do |f| %>
    <%= f.text_field :name, :class => "form-input", :placeholder => 'Name' %>
    <%= f.text_field :email, :class => "form-input", :placeholder => 'Email' %>
    <%= f.password_field :password, :class => "form-input", :placeholder => 'Password'  %>
    <%= f.password_field :password_confirmation, :class => "form-input", :placeholder => "Confirm password" %>
    <%= f.submit "Create Account", :class => "form-button" %>
  <% end %>
</div>

app/views/users/edit.html.erb
  <p id="standard-page-title">Create Account</p>
</div>
<%= render 'layouts/flash_errors' %>
<%= render 'form' %>

app/views/users/new.html.erb
  <p id="standard-page-title">Create Account</p>
</div>
<%= render 'layouts/flash_errors' %>
<%= render 'form' %>

app/views/users/show.html.erb
  <p id="profile-page-title"><%= @user.name %> 
    <span id="user-email">
      (<%= mail_to @user.email %>)
      <% if current_user == @user %>
        - <%= link_to "edit profile", edit_user_path(@user) %>
      <% end %>
    <span>
  </p>
</div>

<div class="section-box">
  <div class="section-header"><%= pluralize(@user.questions.length, 'Question') %>:</div>
  <%= render 'questions/index', :questions => @user.questions %>
</div>

<div class="section-box">
  <div class="section-header"><%= pluralize(@user.answers.length, 'Answer') %>:</div>
  <% @user.answers.each do |answer| %>
    <div class="user-answer">
      <%= link_to answer.question.title, answer.question, :class => "question-title" %>
      <%= render 'answers/answer', { :answer => answer, :@comment => Comment.new } %>
    </div>
  <% end %>
</div>

app/views/votes/_num_votes.html.erb
<div id="num-votes"><%= voteable.vote_count %></div>
<div class="word-votes"><%= voteable.vote_count == 1 ? "vote" : "votes" %></div>

app/views/votes/_vote.html.erb
<div class="vote-buttons" data-vote-value='<%= current_user.vote_value(voteable) %>' data-vote-id="<%= current_user.vote_id(voteable) %>">

  <%= link_to image_tag('up_arrow.png', height: "15", width: "20"), 
      votes_path(:vote => { :voteable_type => voteable.class.name, 
                            :voteable_id => voteable.id, value: 1 }), 
      :method => :post, 
      remote: true, 
      :class => "up" %>
  
  <%= link_to image_tag('down_arrow.png', height: "15", width: "20"), 
      votes_path(:vote => { :voteable_type => voteable.class.name, 
                            :voteable_id => voteable.id, value: -1 }), 
      :method => :post, 
      remote: true, 
      :class => "down" %>

</div>

app/views/votes/_vote_box.html.erb
<div class="votes-box">
  <%= render 'votes/num_votes', voteable: voteable %>
</div>
<% if current_user %>
  <%= render 'votes/vote', voteable: voteable %>
<% end %>